### PR TITLE
Python message extractor respects unicode_literals in __future__

### LINKED ISSUE #426: Python message extractor doesn't respect unicode_literals in __future__
`extract_python` of Babel doesn't respect `from __future__ import unicode_literals` in Python 2.x.  With the below example code:

```python
# coding: utf-8
from __future__ import unicode_literals
_('\xa0')
```

We get this encoding error:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 10: invalid start byte
```

A workround is to use `u''` literals explicitly:

```python
# coding: utf-8
from __future__ import unicode_literals
_(u'\xa0')
```

### PR DESCRIPTION
**Pull request by sublee**
This patch fixes #426.

### CODE REVIEW

**Comment by akx** [comment]
The two commits should be squashed into one, since the second seems to just add Py3.5 compatibility which was lacking in the first commit.

Looks fine to me otherwise. :)

**Comment by sublee** [comment]
@akx Thank you for reviewing my patch.  I squashed my commits as you advised.  Please review again.

**Comment by akx** [comment]
Thanks for the patch, @sublee! :)

**Comment by sublee** [comment]
@akx Thank you for accepting it! :)

**Pull request merged**
