### PR TITLE
Fixes good comments link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by narayanacharya6**
Fixes the dead link with a new link to the same resource. Original issue [#345](https://github.com/python-babel/babel/issues/345) .

### CODE REVIEW

**Comment by akx** [comment]
Can you explain the difference between `coala-red` and `coala`?

**Comment by narayanacharya6** [comment]
I don't have a good explanation for that actually. I just did a quick google search of "coala writing good commits" and stumbled on a link with a very similar domain name and following URL. Anything else I need to check?

**Comment by Linkid** [comment]
If you want a more recent link, you can use this one: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html.

**Comment by narayanacharya6** [comment]
Thanks @Linkid, I will update the link.

**Comment by akx** [comment]
@narayanacharya6 Please squash the two commits and we're good to go. :)

**Pull request merged**
