### PR TITLE
Add a format_list function

### PR DESCRIPTION
**Pull request by mbirtwell**
Adds a format_list function which formats a python list according to the locale e.g. ['a', 'b', 'c'] will be formatted as "a, b and c" in english or "a、b和c" in chinese.

### CODE REVIEW

**Comment by sils1297** [comment]
@mbirtwell very cool! Needs review.

**Comment by sils1297** [comment]
@mbirtwell please address the comments so I can merge this. This is really useful!

**Comment by mbirtwell** [comment]
I've just noticed the ci failures, I don't think I got any notifications for them. They don't appear to be related to the change though. They are permission errors accessing a pip related file on some Mac builds. Is it possible that it's a build system configuration problem.

**Comment by sils1297** [comment]
@mbirtwell that looks nondeterministic indeed, sadly this happens sometimes not fully sure about the reasons. I retriggered the build.

**Comment by sils1297** [comment]
@mbirtwell there you go, all is well :)

**Comment by sils1297** [comment]
@mbirtwell would you mind squashing your last two commits together for a cleaner history?

**Comment by mbirtwell** [comment]
This failure doesn't seem related to my change. It's a failure in a test on pot file generation. Is it possible to retrigger the tests again. I can't work out if I can do it myself.

**Comment by sils1297** [comment]
@mbirtwell you can retrigger all builds by `git commit --amend` your commit, saving it with the same message (note that git will give it a new SHA so you'll create a new commit with the same contents) and `push --force` it up so all builds will restart.

Sorry for those CI failures, we do need to investigate that... if somebody ever finds the time...

**Comment by sils1297** [comment]
see https://github.com/python-babel/babel/issues/275

**Pull request merged**
