### PR TITLE
2.3.4

### PR DESCRIPTION
**Pull request by akx**

### CODE REVIEW

**Comment by sils1297** [comment]
which are cherry picked and already reviewed?

**Comment by akx** [comment]
@sils1297 All changes here are already in master.

**Comment by akx** [comment]
@sils1297 : Namely,

* changes in c4056d2 are from fbc1648 and 414aec5..ee8abd6 (CR in#386 and #389 respectively)
* f8ada14 is cherry-pick of 670a84e (CR in #393)

**Comment by akx** [comment]
Bah, it seems I fudged up the cherry-pick somehow. Just a moment...

**Comment by sils1297** [comment]
why does the commit message of https://github.com/python-babel/babel/pull/394/commits/f61910287e7f841675d0473596003d834dc1b165 have no reason? Can you please never merge a revert without a reason?

**Comment by akx** [comment]
@sils1297 Sure thing, will mandate refs in revert commit messages in the future. (GitMate rule idea? :) )

For that particular bug, see #391 anyway.

**Comment by akx** [comment]
@sils1297 I added a refs to the revert message here.

**Comment by sils1297** [comment]
thanks, filed https://github.com/coala-analyzer/coala-bears/issues/337. We also added an option to detect non imperative tense for commit messages :)

**Comment by sils1297** [comment]
ack b4d95cd fe2e6e4 915236c

**Comment by sils1297** [comment]
@akx feel free to merge and release :)

**Pull request merged**
