### PR TITLE
Add CONTRIBUTING

### PR DESCRIPTION
**Pull request by sils1297**
This finally fixes our review process and gives users a bug template.

### CODE REVIEW

**Comment by sils1297** [comment]
@etanol @erickwilder whoever comes first, could you please self assign and review this? If you're fine with the PR, please try using dropping a plain `@rultor merge` command and see if this works.

**Comment by erickwilder** [comment]
I think that the right home of this file is inside of the `docs/` directory (as an `.rst` not `.md` file), this way the contributing guidelines will be available at `babel.pocoo.org` too.

**Comment by sils1297** [comment]
This way they will be picked up by github, see
https://github.com/blog/1184-contributing-guidelines

2015-09-23 17:15 GMT+02:00 Erick Wilder <notifications@github.com>:

**Comment by erickwilder** [comment]
How about not using markdown, use RST without the `.rst` extension, the same way that `CHANGES` is used?
https://github.com/python-babel/babel/blob/master/docs/changelog.rst#L1

This way we address 2 issues: keep the main source of the documentation (babel.pocoo.org) updated with the contributing guidelines too.

**Comment by sils1297** [comment]
That's actually a good idea though I don't like RST. Still it's a good idea and thus I'll do it :)

**Comment by sils1297** [comment]
Hey, what you desire is done here: https://github.com/python-babel/babel/blob/sils/contributing_rst/CONTRIBUTING

However, I actually find the initial solution to be better, *because*:

- Markdown is way better readable in GitHub. RST isn't very good in plain text, links are weird and most importantly one cannot simply copy the bug template without hassle (on github)!
- Users will rather read this file on GitHub than in the official docs. The official docs could link to this but I think it makes sense to optimize readability for Markdown/Plain Text.

**Comment by erickwilder** [comment]
I understand your point. But using RST is not a big deal, it's already used in the project (and most of the Python community is comfortable with it) and readability of plain RST files are not so different from Markdown. 
Also, we shouldn't took any project decision based on the fact of being hosted by Github. A comment I've seen before:
>  "Github could be the next Sourceforge"
And that's true.

**Comment by sils1297** [comment]
> Also, we shouldn't took any project decision based on the fact of being hosted by Github. A comment I've seen before:
> >  "Github could be the next Sourceforge"
> 
> And that's true.

Heh what a comment. :) Good catch. However, changing the document to whatever one might switch to in the future is not a problem. I did this comment when dealing with commit messages which are "meant to be forever" because they're by definition our history and we want our history to be browsable at all times even if we switch in the future. This does not apply to this document which should be tailored to our current needs. As of now we *are* using GitHub and people checking out this repository will IMO most likely view this document on GitHub. Having it in the documentation *at all* is not needed IMO because the docs are for users of Babel.

> readability of plain RST files are not so different from Markdown.

So my main concern is the code block with is way better to copy in plain text with the three backticks. Secondly for me personally (just one statistical data point here) markdown is way better readable because it seems to be a little more leightweight but still very expressive. As mentioned befre I'm not a sphinx expert *at all* so I might be missing an alternative syntax or so.

**Comment by erickwilder** [comment]
If you want to use Markdown, so be it. Just for the record, it's not what I'd do

**Comment by erickwilder** [comment]
@sils1297 Could you rebase this one, after that we can merge.

**Comment by sils1297** [comment]
> If you want to use Markdown, so be it. Just for the record, it's not what I'd do

Ok, this seems to be really an opinion thing, fwiw I have nothing against being convinced towards the better solution.

> Could you rebase this one, after that we can merge.

So I'd like to retry rultor on this one because the merging of the maintenance branch does not work presumably because of a rultor bug which I suspect doesn't apply here - if that works than I wouldn't need the additional rebase as rultor would do that for me. So I'll try that out :)

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Ok, that's what I wanted to know - GitHub is a pain in the ass... but I can work around that.

**Comment by sils1297** [comment]
@rultor merge again please, this time it might work.

**Pull request merged**
