### PR TITLE
GAE optimisation

### PR DESCRIPTION
**Pull request by sys-git**
Hi, I've re-forked and created this gae-optimised branch (reading many files from the file system introduces a significant lag when an instance receives it's warmup request, there is also a file limit which we cannot breach - this does it's best to reduce the number of files).
I've run tox across all targets except pypy (which I haven't installed).
I'd be interested to hear your thoughts.

### CODE REVIEW

**Comment by erickwilder** [comment]
Hi @sys-git,

Sorry for the huge delay to give you feedback. We're trying to give as much attention as we can to the project.
This is a very long PR, nice work! After reviewing your code and testing (even on PyPy) everything is OK to me. I'm promoting this to `partial approved`. 
One more thing to change: can you add a short description of your work to our `CHANGES` file (under the 3.x version)? This way we can keep track of the contents of our next release.

Thank you again for you contribution :+1:

**Comment by sils1297** [comment]
@sys-git can you rebase and add the CHANGES note as asked by @erickwilder ?

**Comment by sys-git** [comment]
Will do within the next day.
Regards.

On Mon, Sep 21, 2015 at 1:25 pm, python-babel/babel
<reply@reply.github.com>
wrote:
@sys-git [https://github.com/sys-git] can you rebase and add the CHANGES note as asked by @erickwilder [https://github.com/erickwilder] ?

—
Reply to this email directly or view it on GitHub
[https://github.com/python-babel/babel/pull/198#issuecomment-141957028] .[https://github.com/notifications/beacon/ACxFu8jyVnad6W9goeeGPIvW_VcwA6EHks5oz-7HgaJpZM4FnM9j.gif]

**Comment by sils1297** [comment]
@sys-git any progress?

**Comment by sys-git** [comment]
Ah, sorry. Been really busy. Will do this weekend.
Regards

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.0.46&pv=8.3]
On Fri, Oct 2, 2015 at 3:19 pm, python-babel/babel
<reply@reply.github.com>
wrote:
@sys-git [https://github.com/sys-git] any progress?

—
Reply to this email directly or view it on GitHub
[https://github.com/python-babel/babel/pull/198#issuecomment-145034212] .[https://github.com/notifications/beacon/ACxFuzXIUJijl0zDu3CDJPSH4ccm7Em6ks5o3onWgaJpZM4FnM9j.gif]

**Comment by akx** [comment]
Closing this as age-old and cobwebbed 🕸 .

I think GAE is increasingly a niche use case these days, and the ideas in this PR are better implemented as part of the planned loader API for Babel 3 (whenever it appears).

**Pull request closed without merging**
