### PR TITLE
Improved JavaScript extraction

### PR DESCRIPTION
**Pull request by akx**
This PR improves the JavaScript message extraction system, adding support for 

* dotted names as keywords (`com.corporate.i18n.gettext`) (#148)
* tokenization of JSX/E4X `<tag>`s (to avoid misparses) (#280)
* ES6 template strings in two different flavors (#329)

It's a refactor and superset of the previous JavaScript PRs, so:

Closes #298 
Closes #310

### CODE REVIEW

**Comment by zackargyle** [comment]
This looks fantastic. Thanks for adding further support!

**Comment by catmeme** [comment]
Any progress on this? I am in need of dotted names as keywords. Thanks.

**Comment by akx** [comment]
@catmeme If you feel like it, could you give the PR a quick code review pass?

**Comment by RauliL** [comment]
LGTM.

**Comment by akx** [comment]
Merging. (@RauliL is a colleague who I recruited to do CR.)

**Comment by zackargyle** [comment]
@akx, any chance you could update the pip package? We're ready to try out the new JSX extraction!

**Comment by lyapun** [comment]
@akx Yeah, we are waiting for this too :)

**Comment by sassanh** [comment]
@akx thanks for this great package. Unfortunately seems like the jsx support is not complete, it doesn't work on something like this:

    <input ref='login-email' placeholder={gettext('username')}/>

is it the same for you or am I missing a config?

**Comment by sassanh** [comment]
@akx nevermind, I downloaded latest dev version (2.4.0-dev) and it's fixed.
It'd be great if you'd add make install in setup.py so that when someone installs a `git commit` using `pip` it generates `locale-data`.

**Pull request merged**
