### PR TITLE
Changes discussed on #261

### PR DESCRIPTION
**Pull request by upman**
Script to update AUTHORS file automatically
Replace author mentions with 'The babel authors'

### CODE REVIEW

**Comment by akx** [comment]
I think `the Babel authors` would be a nicer capitalization.

**Comment by etanol** [comment]
I agree, `Babel` is used capitalized in the `README` file.  @upman just change that and we'll merge this.

**Comment by upman** [comment]
@etanol Fixed. Have a look.

**Comment by etanol** [comment]
Fine, I'll let @sils1297 merge this one, since he's the operations guy.

**Comment by sils1297** [comment]
Thanks, will look at this soon

**Comment by sils1297** [comment]
Hi, some comments on the commits, thanks for your contribution! Ping me if you need any assistance.

**Pull request closed without merging**
