### PR TITLE
Add f-string parsing for Python 3.12 (PEP 701)

### PR DESCRIPTION
**Pull request by encukou**
Since Python 3.12, f-strings are tokenized and parsed like the rest of Python's grammar, using the new tokens `FSTRING_START`, `FSTRING_MIDDLE` and `FSTRING_END`, as described in [pep 701 #new-tokens](https://peps.python.org/pep-0701/#new-tokens).

Make the babel message extractor concatenate these three if they're adjacent to each other. If they're not, that means there are dynamic substitutions, so the f-string is ignored.

### CODE REVIEW

**Comment by encukou** [comment]
Not sure if y'all want to add 3.12 to the CI yet?
For that to pass [setuptools will need to be added to tox.ini](https://github.com/python-babel/babel/issues/1005#issuecomment-1728105742) as it's needed in the data setup.

**Comment by mgorny** [comment]
Thanks. I can confirm that with this patch, the tests pass both on 3.11 and 3.12.

**Review by akx — APPROVED** [review]
LGTM! I tested this locally on 3.12 and seems to work great. I took the liberty of fixing the lint fail too.

**Comment by akx** [comment]
> Not sure if y'all want to add 3.12 to the CI yet? For that to pass [setuptools will need to be added to tox.ini](https://github.com/python-babel/babel/issues/1005#issuecomment-1728105742) as it's needed in the data setup.

Working on that in #1028 :)

**Comment by BrentHuang** [comment]
how to use?  In babel 2.14.0, the code can't be extracted to .pot file:

```
foo= 'Hardy'
print(_(f"Hello {foo}"))
```

**Comment by BrentHuang** [comment]
> how to use? In babel 2.14.0, the code can't be extracted to .pot file:
> 
> ```
> foo= 'Hardy'
> print(_(f"Hello {foo}"))
> ```

```
foo= 'Hardy'
print(_(f"Hello {foo}"))
```

in the code above, extract ok, but not translated by gettext.

**Pull request merged**
