### PR TITLE
introduce PyInstaller support. Fixes #500

### LINKED ISSUE #500: Using __file__ in a PyInstaller environment is not possible
Babel is not working in my projects which are processed with PyInstaller.
The reason for this: the direct access to "`__file__`".

### PR DESCRIPTION
**Pull request by wodo**

### CODE REVIEW

**Comment by benselme** [comment]
Thanks, that's much better. 

I still think we shouldn't be creating a new module (`pi_support.py`) for just one function.

Sorry for the CI mess. @akx, @etanol, any idea what's happening ?

**Comment by etanol** [comment]
I agree with @benselme:

> I still think we shouldn't be creating a new module (`pi_support.py`) for just one function.

@wodo, can you move the function to `babel/core.py` or `babel/__init__.py`?

**Comment by wodo** [comment]
Yes, I will try to do it.

**Comment by wodo** [comment]
Implementing `get_base_dir` in core.py results in an import cycle

**Comment by benselme** [comment]
What about `babel/__init__.py` then ?

**Comment by wodo** [comment]
Implementing in `babel/__init__.py` results in an import cycle.
The same problem when implementing it in `babel/util.py`.

**Comment by benselme** [comment]
It actually works in `util.py`... I just pushed that change to your PR, and better tests. 

See if it's ok with you, then you can squash yet again, and then we can merge.

Thanks !

**Comment by wodo** [comment]
Hello @benselme,
Thanks, but the appveyor is reporting the same troubles...
Its not working.

**Comment by benselme** [comment]
Ha I see ! The tests pass locally, but it's setup.py that crashes. You're right, that's not good. Let me look into that a bit more. `localedata` is not a great place for `get_base_dir` either.

**Comment by wodo** [comment]
I close this PR and will open a follow up.
Using `babel/core.py` or `babel/util.py` seems not possible.
I'm not able to squashig all this stuff...

**Pull request closed without merging**
