### PR TITLE
Upgrade to CLDR 31

### PR DESCRIPTION
**Pull request by akx**
Yay, new CLDR!

### CODE REVIEW

**Comment by sils** [comment]
@akx I can't review this right now, if you think it's good it's probably best to just merge this or find someone else :/ super stressed

**Comment by akx** [comment]
@sils Hey, no worries, man :)

**Comment by bdeeney** [comment]
+1  We have a project that currently uses babel and would immediately benefit from an update to the most recent CLDR.

@akx / @jtwang - are there any obstacles to merging and releasing this PR?  If there is anything I can do to help with testing, etc., please let me know.  Thanks!

**Comment by akx** [comment]
@bdeeney I'm going to just merge this now, so if you want to help with testing, you could build Babel off the master branch and try it with yourself code. If you want, I can also build a wheel off master for you.

**Pull request merged**
