### PR TITLE
Refactor CLDR importer script

### PR DESCRIPTION
**Pull request by akx**
The CLDR importer script was mostly one function of nearly 500 lines, which was frankly silly.

This PR breaks it into multiple functions that do one bit of importing before passing on the proverbial torch to another import function, et cetera. The script behaves exactly as before wrt the resulting locale data files, though!

As the commit messages say,

> Special care was taken to order the new functions in the same order as the original source was; the resulting whitespace-ignoring diff is very minimal.

So, before you are too daunted to review this, **please use `git diff -w` or the `?w=1` query parameter on GitHub:**

```shell
$ git diff --stat master
 scripts/import_cldr.py | 929 +++++++++++++++++++++++++------------------------
 1 file changed, 474 insertions(+), 455 deletions(-)

$ git diff --stat -w master
 scripts/import_cldr.py | 199 +++++++++++++++++++++++++++----------------------
 1 file changed, 109 insertions(+), 90 deletions(-)
```

### CODE REVIEW

**Comment by jtwang** [comment]
One thing that would help me immensely is to split argument parsing out of the main method. It's a patch we've been applying in our fork in order to build successfully.

Totally OK if you want to punt on this, I can make the change myself later on. :)

```
def import_cldr(srcdir, destdir, force=False, dump_json=False):
   # blah blah blah

if __name__ == '__main__':
     # blah blah parse arguments
     import_cldr(srcdir, destdir, force, dump_json)
```

**Comment by jtwang** [comment]
Done a round of reviews, love this change!

**Comment by jtwang** [comment]
Looks good, other than the unused arg. Fix and ship!

**Comment by jtwang** [comment]
Oh, yes, mega thanks for splitting argparsing and processing logic! <3 <3

**Comment by akx** [comment]
Merging based on previous greenlight :)

**Pull request merged**
