### PR TITLE
Allow passing a callable to `extract()`

### PR DESCRIPTION
**Pull request by akx**
This makes it much easier to do create custom extraction machinery without having to bother with external configuration files or Setuptools entry points.

### CODE REVIEW

**Comment by sils1297** [comment]
@akx hey, thanks for trying to help us! Please note that we're short of manpower, if you'd like to help please also consider reviewing other peoples PRs.

Your commit seems not to be compatible with Python 3.3 and lower, see https://travis-ci.org/python-babel/babel/jobs/97957737 . Could you fix that?

**Comment by akx** [comment]
My bad for not running tests on Py3! (Turns out it was an one byte fix (`""` to `b""`).

Anyway, I'd be glad to help in other ways too. :)

**Comment by sils1297** [comment]
@akx awesome, just pick one or a few of https://github.com/python-babel/babel/pulls?q=is%3Aopen+is%3Apr+label%3A%22%283%29+pending+review%22 , if you think the PR is good for the project, drop a comment. General rules, all tests must pass of course, more coverage is good, good commit messages are valued.

**Comment by sils1297** [comment]
Thanks! Added note to https://github.com/python-babel/babel/wiki/CHANGES

**Comment by sils1297** [comment]
@akx you might want to join our chat at https://gitter.im/python-babel/babel :)

**Pull request merged**
