### PR TITLE
Refactored frontend module and removed duplicate code

### PR DESCRIPTION
**Pull request by bacher09**
Frontend module repeats  functions for distutils and cli interface, I tried to merge this parts of code.

### CODE REVIEW

**Comment by sils1297** [comment]
@bacher09 many thanks for taking the time to make a PR!

Can you rebase the PR and fix the issue pointed out?

**Comment by bacher09** [comment]
Sorry for delay. I rebased PR and fixed issue, but it seems that patch little bit outdated and I also should update it, to make it merge without conflicts.

**Comment by erickwilder** [comment]
@bacher09 
Ping me if you need any help here.

**Comment by akx** [comment]
This was closed by #311.

Thanks for the inspiration @bacher09 !

**Pull request closed without merging**
