### PR TITLE
setup.cfg: Use universal wheel

### PR DESCRIPTION
**Pull request by sils1297**
@etanol this one too

### CODE REVIEW

**Comment by etanol** [comment]
Sorry, I took a bit long to see this.  As I mentioned, I'm in the middle of a relocation.

@sils1297  I think you were too quick to merge this one.  The generated wheel is missing the `localedata/__init__.py` due to the data files definition in `setup.py`.  I think the easy fix would be to move the data files to a different subdirectory, or to refactor the code and rename the `babel.localedata` module/package.

I'm checking the 2.x branch but that one will probably work if it doesn't contain the `babel.localedata` module is still in the `localedata.py` file.

**Comment by sils1297** [comment]
> Sorry, I took a bit long to see this.

Ah, I merged because the other one got approved and they're essentially the same. We also need review policies...

**Comment by etanol** [comment]
Related commit: 7d387f95f4f41ed646bcb2b4fa39dae4a601b6ce

**Comment by sils1297** [comment]
@etanol would you mind joining https://gitter.im/python-babel/babel for a talk? We need to organize a bit.

**Pull request merged**
