### PR TITLE
Empty Commit

### PR DESCRIPTION
**Pull request by sils1297**
This commit exists solely to test the new rultor pipeline and has no
further purpose or contents.

### CODE REVIEW

**Comment by erickwilder** [comment]
@rultor merge

**Comment by sils1297** [comment]
Temporary workaround: https://github.com/python-babel/babel/pull/252 , we should try merging the empty commit after merging that one to test if the rebase works properly, one step at a time :)

**Comment by sils1297** [comment]
@rultor merge please.

**Comment by sils1297** [comment]
@rultor config

**Comment by sils1297** [comment]
So this is definitely a rultor bug.

**Comment by sils1297** [comment]
Ok this is a bad test PR because empty commits are apparently not applied during rebase :)

**Pull request closed without merging**
