### PR TITLE
Change to using include_package_data

### PR DESCRIPTION
**Pull request by gutsy**
for issue #260. I am new to python so please let me know if I did not do this correctly.

### CODE REVIEW

**Comment by sils1297** [comment]
hey, many thanks. A review will happen soon.

**Comment by sils1297** [comment]
@gutsy hey, you didn't try it out I guess? Would you do us the pleasure to do this? As you see our continuous integration services fail because installation doesn't work. (Btw. in python it's `True` and not `true`) When you do the correction please `git commit --amend` your commit and `push --force` onto the branch so we won't have all those "oops, reviewer found another thing" commits cluttering our history. Normal procedure :)

Let us know if we can help you further - thanks for your contribution!

**Comment by gutsy** [comment]
@sils1297 How do you try this project out? I'm normally a java dev so this is all pretty new to me, but I want to learn Python more. I couldn't find how to actually "run" it for testing.

**Comment by sils1297** [comment]
@gutsy would you mind joining me in https://gitter.im/python-babel/babel for a talk? :)

**Comment by sils1297** [comment]
@gutsy as for this particular problem, you're working with the setup file so to test it you try installing babel - that is `python setup.py install`

**Comment by sils1297** [comment]
Looks good apart from that! You can now simply `git commit --amend`to change the message. Please add a comment after you push again so we know when to restart the review.

**Comment by gutsy** [comment]
fixed commit message and pushed

**Comment by gutsy** [comment]
fixed commit message and pushed

**Comment by gutsy** [comment]
fixed commit message and pushed

**Comment by sils1297** [comment]
@gutsy as for the commit message: could you take a look at those guidelines? There are several hard requirements not fulfilled. The "Fixes" line e.g. belongs in the body and the first line must not exceed 50 chars.

**Comment by gutsy** [comment]
@sils1297 Ok, I think I have it now, just pushed.

**Comment by sils1297** [comment]
@gutsy awesome! FWIW ideally you'd shorten the first line a bit more `setup: Use include_package_data` would be a bit shorter and faster to read. No need for changing that now :)

This is approved now and will be merged after CI services have finished. Thanks for your contribution!

**Pull request merged**
