### PR TITLE
Fix for mitsuhiko/babel#133.

### LINKED ISSUE #133: Tests failure with newer pytz versions
Three tests fail with versions of pytz>=2014.4

From the [pytz docs](http://pytz.sourceforge.net/#localized-times-and-date-arithmetic):

    Unfortunately using the tzinfo argument of the standard datetime constructors
    ‘’does not work’’ with pytz for many timezones.

So I think that the way those tests are written is broken.

    =================================== FAILURES ====================================
    ___________________ DateTimeFormatTestCase.test_timezone_gmt ____________________

    self = <tests.test_dates.DateTimeFormatTestCase testMethod=test_timezone_gmt>

	def test_timezone_gmt(self):
	    tz = timezone('Europe/Berlin')
	    t = time(15, 30, tzinfo=tz)
	    fmt = dates.DateTimeFormat(t, locale='de_DE')
    >       self.assertEqual('GMT+01:00', fmt['ZZZZ'])
    E       AssertionError: 'GMT+01:00' != 'GMT+00:53'
    E       - GMT+01:00
    E       + GMT+00:53

    tests/test_dates.py:188: AssertionError
    __________________ DateTimeFormatTestCase.test_timezone_rfc822 __________________

    self = <tests.test_dates.DateTimeFormatTestCase testMethod=test_timezone_rfc822>

	def test_timezone_rfc822(self):
	    tz = timezone('Europe/Berlin')
	    t = time(15, 30, tzinfo=tz)
	    fmt = dates.DateTimeFormat(t, locale='de_DE')
    >       self.assertEqual('+0100', fmt['Z'])
    E       AssertionError: '+0100' != '+0053'
    E       - +0100
    E       + +0053

    tests/test_dates.py:182: AssertionError
    _____________________________ test_get_timezone_gmt _____________________________

	def test_get_timezone_gmt():
	    dt = datetime(2007, 4, 1, 15, 30)
	    assert dates.get_timezone_gmt(dt, locale='en') == u'GMT+00:00'
	
	    tz = timezone('America/Los_Angeles')
	    dt = datetime(2007, 4, 1, 15, 30, tzinfo=tz)
    >       assert dates.get_timezone_gmt(dt, locale='en') == u'GMT-08:00'
    E       assert 'GMT-08:07' == 'GMT-08:00'
    E         - GMT-08:07
    E         ?         ^
    E         + GMT-08:00
    E         ?         ^

    tests/test_dates.py:384: AssertionError

### PR DESCRIPTION
**Pull request by benselme**
Fixes the tests that failed with the newer versions of pytz. Fixes #133

### CODE REVIEW

**Comment by jrfern** [comment]
No news is bad news, and this bug prevents the fix for many other bugs. What can be done, @benselme?

**Comment by sils1297** [comment]
@jrfern I don't understand your comment fully.
@benselme can you rebase the PR onto current master, correct the reference to point to bug https://github.com/mitsuhiko/babel/issues/106 (as it was a duplicate, please use full URL, avoid relying on users viewing the commit message via GitHub), add an explanation so the commit message is valid on its own (it should be, the issue link should provide more information about the issue while the commit message itself should provide enough information to explain the *change* (not the fix) to the code and justify it.) Take a look at http://coala.readthedocs.org/en/latest/Getting_Involved/Writing_Good_Commits/ for a summary of common commit message guidelines.

**Comment by sils1297** [comment]
@benselme still around? I can understand frustration of your PR being ignored for such a long time. We took over maintenance shortly ago because the old maintainer (obviously) didn't have enough time to maintain this repo properly. I can assure you, that we will work together with you to get this merged.

@jrfern you seem to be interested in this issue, if @benselme is not around anymore, would you like to ramp this one up to our current standards and submit a replacement PR? We currently don't have the manpower to do more than triaging issues and reviewing and merging PRs because they stacked up pretty high.

**Comment by benselme** [comment]
I just came back from a long trip. I'll try to fix that PR this week.

**Comment by sils1297** [comment]
@benselme cool, many thanks!

**Comment by benselme** [comment]
Hasn't this been fixed in https://github.com/mitsuhiko/babel/commit/9f099d39553188d9bc56f7721ea40ece9f0959cd already ?

**Comment by etanol** [comment]
@benselme fixed indeed.  Closing.

**Pull request closed without merging**
