### PR TITLE
Add `flake8` pre-commit hook and applied fixes

### PR DESCRIPTION
**Pull request by lukas-b**
Added `flake8` and `reorder-python-imports` [pre-commit](https://github.com/pre-commit/pre-commit) [hooks](https://github.com/pre-commit/pre-commit-hooks) and applied fixes.

### CODE REVIEW

**Comment by akx** [comment]
I much preferred the old import style (all imports from a single module on the same line).

The `isort` (https://github.com/timothycrosley/isort) project supports that style . . . could `reorder-python-imports` do that too?

**Comment by lukas-b** [comment]
> I much preferred the old import style (all imports from a single module on the same line).

Makes sense, it's also what [pep-0008/#imports](https://www.python.org/dev/peps/pep-0008/#imports) suggests.

> could `reorder-python-imports` do that too?

Not at the moment, via [reorder_python_imports](https://github.com/asottile/reorder_python_imports):

> Splits from imports (may be configurable in the future!)

I'll revert the `reorder-python-imports` part (will also add support for `all imports from a single module on the same line`).
Does the `flake8` part look good?

Thanks! :)

**Comment by akx** [comment]
@lukas-b Yup, the flake8 bits look sensible to me. :)

**Comment by lukas-b** [comment]
@akx Cool, updated, thanks! :)

**Comment by lukas-b** [comment]
@akx The [single travis-ci failure](https://travis-ci.org/python-babel/babel/builds/114621852) is due to a flaky test (time-based), see `POT-Creation-Date: 2016-03-08 21:03+0000` vs `POT-Creation-Date: 2016-03-08 21:02+0000` in [output](https://travis-ci.org/python-babel/babel/builds/114621852):

```python
'# Translations template for TestProject.\n# Copyright (C) 2016 FooBar, Inc.\n# This file is distributed under the same license as the TestProject\n# project.\n# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.\n#\n#, fuzzy\nmsgid ""\nmsgstr ""\n"Project-Id-Version: TestProject 0.1\\n"\n"Report-Msgid-Bugs-To: bugs.address@email.tld\\n"\n"POT-Creation-Date: 2016-03-08 21:03+0000\\n"\n"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"\n"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"\n"Language-Team: LANGUAGE <LL@li.org>\\n"\n"MIME-Version: 1.0\\n"\n"Content-Type: text/plain; charset=utf-8\\n"\n"Content-Transfer-Encoding: 8bit\\n"\n"Generated-By: Babel 2.2.0.dev0\\n"\n\n#. TRANSLATOR: This will be a translator coment,\n#. that will include several lines\n#: project/file1.py:8\nmsgid "bar"\nmsgstr ""\n\n#: project/file2.py:9\nmsgid "foobar"\nmsgid_plural "foobars"\nmsgstr[0] ""\nmsgstr[1] ""\n\n#: project/ignored/this_wont_normally_be_here.py:11\nmsgid "FooBar"\nmsgid_plural "FooBars"\nmsgstr[0] ""\nmsgstr[1] ""\n\n'
'# Translations template for TestProject.\n# Copyright (C) 2016 FooBar, Inc.\n# This file is distributed under the same license as the TestProject\n# project.\n# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.\n#\n#, fuzzy\nmsgid ""\nmsgstr ""\n"Project-Id-Version: TestProject 0.1\\n"\n"Report-Msgid-Bugs-To: bugs.address@email.tld\\n"\n"POT-Creation-Date: 2016-03-08 21:02+0000\\n"\n"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"\n"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"\n"Language-Team: LANGUAGE <LL@li.org>\\n"\n"MIME-Version: 1.0\\n"\n"Content-Type: text/plain; charset=utf-8\\n"\n"Content-Transfer-Encoding: 8bit\\n"\n"Generated-By: Babel 2.2.0.dev0\\n"\n\n#. TRANSLATOR: This will be a translator coment,\n#. that will include several lines\n#: project/file1.py:8\nmsgid "bar"\nmsgstr ""\n\n#: project/file2.py:9\nmsgid "foobar"\nmsgid_plural "foobars"\nmsgstr[0] ""\nmsgstr[1] ""\n\n#: project/ignored/this_wont_normally_be_here.py:11\nmsgid "FooBar"\nmsgid_plural "FooBars"\nmsgstr[0] ""\nmsgstr[1] ""\n\n'
```

**Comment by akx** [comment]
@lukas-b Cheers :)

**Comment by lukas-b** [comment]
Thanks @akx ! :)
:rocket:

**Pull request merged**
