### PR TITLE
Typo.

### PR DESCRIPTION
**Pull request by kdeldycke**

### CODE REVIEW

**Comment by sils1297** [comment]
@etanol assigning you for review as this affects your code. @kdeldycke the commit message isn't really expressive. At least `numbers: Correct typo` would be nice :)

**Comment by kdeldycke** [comment]
oops. Fucked up my PR. :(

**Comment by kdeldycke** [comment]
Everything's now clean and tidy. Sorry for the delay.

**Comment by etanol** [comment]
Ouch! Too bad the test suite doesn't cover natural language in docstrings ^_^

**Comment by sils1297** [comment]
FWIW we could do at least a grammar check using my beloved coala (
coala-analyzer.org) :P

2015-09-28 19:59 GMT+02:00 Isaac Jurado <notifications@github.com>:

**Pull request merged**
