### PR TITLE
2.1 release preparation

### PR DESCRIPTION
**Pull request by erickwilder**
This PR just adds entries to the `CHANGES` file in order to prepare the `2.1` release.

### CODE REVIEW

**Comment by erickwilder** [comment]
@sils1297, requested changes made

**Comment by sils1297** [comment]
@erickwilder you forgot to change the date to tomorrow

**Comment by erickwilder** [comment]
@sils1297 it's done. Sorry for the delay, i'm with connection problems today.

**Comment by sils1297** [comment]
@rultor merge please

**Comment by erickwilder** [comment]
I think we'll need to manually merge things here until we figure out how to make rultor works

**Comment by sils1297** [comment]
@erickwilder yes, we do. I think this is actually a rultor bug - https://github.com/yegor256/rultor/issues/935 .

**Pull request merged**
